Resources/doc/custom_provider.rst
Resources/doc/custom_renderer.rst
Resources/doc/events.rst
Resources/doc/i18n.rst
Resources/doc/index.rst
Resources/doc/menu_service.rst

I've integrated the documentation of this bundle in my local version of symfony.com website and I've found some syntax issues. This Pull Requests fixes those issues and hopefully is the last one related to docs formatting.

Fixed some minor syntax issues in the docs

---

Resources/doc/index.rst

a brace is missing at line 236

Missing an "}" at index.rst

---

Resources/doc/index.rst

current code results in error
Error: Call to a member function addChild() on null
so I added:
$menu->addChild('About Me', array('route' => 'about'));
and then you can add sub menu item "edit profile"

'About me' child does not exist

---

Resources/config/menu.xml
Resources/config/templating.xml
Resources/config/twig.xml
Templating/Helper/MenuHelper.php
Tests/Templating/MenuHelperTest.php
composer.json

This integrates https://github.com/KnpLabs/KnpMenu/pull/189, it has to be merged after that PR was merged.

Update bundle for new templating/twig features

---

Resources/config/templating.xml
Resources/config/twig.xml

There was a bug in #251
closes #282

Fix the service id in references

---

CHANGELOG.md
DependencyInjection/Configuration.php
Resources/doc/i18n.rst
Resources/views/menu.html.twig
Tests/DependencyInjection/KnpMenuExtensionTest.php

Translate menu items by default

---

Resources/doc/index.rst

Include all documents in a toctree

---

Resources/doc/index.rst

fix config doc

---

Resources/config/menu.xml
Templating/Helper/MenuHelper.php
Tests/Templating/MenuHelperTest.php
composer.json

This integrates https://github.com/KnpLabs/KnpMenu/pull/228. (done)
This PR must be merge after the one on KnpMenu library.

Add getCurrentItem method in MenuHelper

---

Resources/doc/events.rst

https://github.com/KnpLabs/KnpMenu/commit/e7ef14a9469545423276e8516196496664429b81

"Removed the methods related to the current uri in ItemInterface "

---

.travis.yml
DependencyInjection/Compiler/AddTemplatePathPass.php
DependencyInjection/KnpMenuExtension.php
Provider/BuilderAliasProvider.php
Tests/DependencyInjection/Compiler/AddTemplatePathPassTest.php
composer.json

Refs https://github.com/KnpLabs/KnpMenu/issues/273

Drop support for PHP < 5.6 and Symfony < 2.7

---

src/Resources/config/menu.xml

Add autowiring for MenuProviderInterface

---

tests/DependencyInjection/Compiler/MenuBuilderPassTest.php
tests/DependencyInjection/Compiler/RegisterMenusPassTest.php

Fix a problem introduced in https://github.com/KnpLabs/KnpMenuBundle/pull/398 (new travis configuration)

Fix for PR#398

---

src/Resources/doc/index.rst

fix docs link

---

docs/custom_provider.rst
docs/custom_renderer.rst

see https://symfony.com/doc/build_errors

fix YAML code examples

---

.travis.yml
composer.json

Added php 8.0 to composer.json for SonataAdminBundle - continuous-integration/travis-ci/pr

Add php8.0 to composer.json

---

.github/workflows/build.yaml

- fix step names for the composer.json validation
- use a pre-installed PHP version for jobs running with the Symfony LTS versions to be faster.

Improve the github actions setup

---

.github/workflows/build.yaml
composer.json

It appears that tests pass and the bundle installs.
I'm working on a small Symfony 7 demo but running into unrelated issues.  But I figured I'd get the ball rolling with these small changes.

allow Symfony 7

---

src/DependencyInjection/KnpMenuExtension.php

fix deprecated extension

---

composer.json
config/twig.xml

profit from the new Twig runtime

---

.github/workflows/build.yaml
composer.json

improve dependencies declaration

---

config/menu.xml

https://symfony.com/doc/current/reference/dic_tags.html#kernel-reset

:sparkles: Add tag "kernel.reset" to matcher to reset cache state between requests
