KnpLabs/KnpMenuBundle

Resources/doc/menu_service.rst

Since Symfony 2.4 better to use [RequestStack](http://symfony.com/blog/new-in-symfony-2-4-the-request-stack) instead of Request.

Replace Request with RequestStack in docs

---

Resources/doc/menu_service.rst

Fix deprecated errors of dependency injection [using a factory to create services](http://symfony.com/doc/current/components/dependency_injection/factories.html)

Fix deprecated errors of dependency injection

---

DependencyInjection/Compiler/MenuBuilderPass.php
DependencyInjection/Configuration.php
KnpMenuBundle.php
Provider/BuilderServiceProvider.php
Resources/config/menu.xml
Resources/doc/disabling_providers.rst
Resources/doc/index.rst
Resources/doc/menu_builder_service.rst
Tests/DependencyInjection/Compiler/MenuBuilderPassTest.php
Tests/Provider/BuilderServiceProviderTest.php

This is an alternative to #272
This code is running in production at Incenteev since 2 years (in a different namespace of course) and I finally took the time to extract it to KnpMenuBundle.
I wrote the documentation about the feature, so you can look at it to see how it works.

Add a menu provider registering builders as services

---

DependencyInjection/Compiler/AddVotersPass.php
Tests/DependencyInjection/Compiler/AddVotersPassTest.php

The order of voters can be important in 2 cases:
- the first voter which does not abstain wins the decision. In case multiple voters can take opposite decisions on the same item, the order is important (this will never happen for matchers shipped in the library as they either match or abstain, but never reject a match)
- the order of matchers can affect performance: if one of the matchers performs an heavy computation, running it after other matchers can avoid calling it when another matcher is taking a decision.
Replaces #268

Add a priority to allow controlling the order of voters

---

Resources/doc/menu_builder_service.rst

Options sent to the MenuBuilder are in 3rd position when calling knp_menu_get

Fix documentation about MenuBuilder as a service

---

Resources/doc/index.rst

symfony 3 does not have a ContainerAware to extend. but anyway that is bad practice and not needed in this case.
continue from #298

adjust documentation to be symfony 3 compatible

---

Resources/doc/index.rst

We recently reenabled the "docs build error reporting" on symfony.com and these are the errors shows for this bundle:
```
var/docs/rst/knplabs-knpmenu-bundle/en/master/index.rst:69: ERROR: Unknown directive type "code-bock".
.. code-bock:: xml
<?xml version="1.0" charset="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
xmlns:knp-menu="http://knplabs.com/schema/dic/menu">
<knp-menu:config
templating="false"
default-renderer="twig"
>
<knp-menu:twig template="knp_menu.html.twig"/>
</knp-menu:config>
</container>
var/docs/rst/knplabs-knpmenu-bundle/en/master/custom_provider.rst:: WARNING: document isn't included in any toctree
var/docs/rst/knplabs-knpmenu-bundle/en/master/custom_renderer.rst:: WARNING: document isn't included in any toctree …
```

Fixed documentation issues

---

Resources/doc/i18n.rst

`xliff` is not a valid value for the `code-block` directive. Let's use `xml` instead: 
Error details:
```
Exception occurred:
File "sphinx/configurationblock.py", line 60, in run
innernode = nodes.emphasis(self.formats[child['language']], self.formats[child['language']])
KeyError: u'xliff'
```

Fixed a code block directive

---

Resources/doc/events.rst

This is probably a leftover from https://github.com/KnpLabs/KnpMenuBundle/commit/8cf6329e63e4bb8a14336c6facaa8d5f48f80f52.

Fix wrong event name in Resources/doc/events.rst

---

CHANGELOG.md
DependencyInjection/Compiler/AddExtensionsPass.php
Tests/DependencyInjection/Compiler/AddExtensionsPassTest.php

in https://github.com/symfony-cmf/menu-bundle/issues/249 we noticed that when we replace knp_menu.factory with an alias, the compiler pass stops working. once i fixed that, i noticed that this compiler pass assumes a method that is not in the FactoryInterface.
with these changes, we can handle an alias and we fail with a better error message than a fatal error at run time when the factory is instantiated.

handle alias for factory and add sanity checks for it

---

Resources/doc/events.rst

I've noticed this class is neither defined nor used anywhere, it looks like it was predecessor of `AppBundle\Event\ConfigureMenuEvent`.

Removed unused dependency from events.rst

---

Resources/doc/events.rst

The class Symfony\Component\DependencyInjection\ContainerAware does not exist.

Replace ContainerAware with ContainerAwareInterface

---

Resources/config/menu.xml

This enables autowiring support for the FactoryInterface, the MatcherInterface and the MenuManipulator.

Add support for Symfony 3.3+ autowiring

---

.travis.yml

This prevents PRs breaking the validity of the composer.json, which would then be rejected by Packagist.
The lock file is not validated, as it is not committed in the repo.

Add validation of the composer.json on Travis

---

.travis.yml

Precise jobs are now running on the old sudo-required infrastructure, which does not have caching. So the directory is not created by the cache layer in this case.

Fix the travis configuration when the cache is not available

---

DependencyInjection/Compiler/AddVotersPass.php
DependencyInjection/KnpMenuExtension.php

This allows people to skip the tag `knp_menu.voter` for their VoterInterface implementations if their services are marked as autoconfigured.

Add support for autoconfiguring menu voters

---

DependencyInjection/Configuration.php
Provider/BuilderAliasProvider.php
Resources/config/menu.xml
Tests/DependencyInjection/KnpMenuExtensionTest.php
Tests/Provider/BuilderAliasProviderTest.php

This starts adapting the code to prepare for Symfony 4:
- mark some services as public explicitly, to account for the change of the default visibility. Many services are not marked as public yet, because they are public only due to internal needs, which won't be needed anymore before the release.
- adapt the BuilderAliasProvider to account for the removal of bundle inheritance
- use the native Twig notation for the default template, to avoid the dependency on the templating component.

First round of Symfony 4 support

---

.travis.yml
DependencyInjection/Compiler/AddExtensionsPass.php
DependencyInjection/Compiler/AddProvidersPass.php
DependencyInjection/Compiler/AddRenderersPass.php
DependencyInjection/Compiler/AddTemplatePathPass.php
DependencyInjection/Compiler/AddVotersPass.php
DependencyInjection/Compiler/MenuBuilderPass.php
DependencyInjection/Compiler/MenuPass.php
DependencyInjection/Compiler/RegisterMenusPass.php
EventListener/VoterInitializerListener.php
KnpMenuBundle.php
Renderer/ContainerAwareProvider.php
Resources/config/menu.xml
Tests/DependencyInjection/Compiler/AddProvidersPassTest.php
Tests/DependencyInjection/Compiler/AddRenderersPassTest.php
Tests/DependencyInjection/Compiler/AddVotersPassTest.php
Tests/DependencyInjection/Compiler/MenuBuilderPassTest.php
Tests/DependencyInjection/Compiler/RegisterMenusPassTest.php
Tests/EventListener/VoterInitializerListenerTest.php
Tests/Provider/BuilderAliasProviderTest.php
Tests/Renderer/ContainerAwareProviderTest.php
composer.json

This PR uses all the new features I added recently to benefit from Symfony 3.3 DI features (allowing to keep menu builders and menus as private services for instance).
Support for older Symfony versions is kept (I want to have at least 1 release of the bundle compatible with the 2.x LTS and supporting KnpMenu 2.3 without deprecations), but support for private services in these places is not available in this case.
Each commit performs a different refactoring, so things are easier to review commit by commit (I could have split these into multiple PRs, but it was harder for me as I was in the train)

Update configuration for KnpMenu 2.3 and Symfony 3.3+

---

src/DependencyInjection/Configuration.php

As there is no update to #396 I'm creating a new PR instead.

Don't use the deprecated interface with Symfony 4.2

---

.gitignore
.php_cs
src/DependencyInjection/Compiler/AddExtensionsPass.php
src/DependencyInjection/Compiler/AddProvidersPass.php
src/DependencyInjection/Compiler/AddRenderersPass.php
src/DependencyInjection/Compiler/AddVotersPass.php
src/DependencyInjection/Compiler/MenuPass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/KnpMenuExtension.php
src/Provider/BuilderAliasProvider.php
src/Provider/BuilderServiceProvider.php
src/Renderer/ContainerAwareProvider.php
src/Templating/Helper/MenuHelper.php
tests/DependencyInjection/Compiler/AddExtensionsPassTest.php
tests/DependencyInjection/Compiler/AddProvidersPassTest.php
tests/DependencyInjection/Compiler/AddRenderersPassTest.php
tests/DependencyInjection/Compiler/AddVotersPassTest.php
tests/DependencyInjection/Compiler/MenuPassTest.php
tests/DependencyInjection/Compiler/RegisterMenusPassTest.php
tests/EventListener/VoterInitializerListenerTest.php
tests/Provider/BuilderAliasProviderTest.php
tests/Provider/ContainerAwareProviderTest.php
tests/Renderer/ContainerAwareProviderTest.php
tests/Templating/MenuHelperTest.php

Being this a Symfony bundle, I think that [Symfony coding standards](https://symfony.com/doc/current/contributing/code/standards.html) should be enforced.
This PR adds a configuration file for php-cs-fixer (and fixes all files)

enforce Symfony coding standards

---

.travis.yml
composer.json
phpunit.xml.dist

- Replace deprecated PHPUnit @expectedException annotations
- Update deprecated use of HttpFoundation events
- Fix Travis config

Support for Symfony 5

---

composer.json

As 4.0 is no longer maintained I suggest to bump the version to 4.2 (the first minor of 4.x main that still receives updates).

Bumped symfony 4 minor version

---

src/DependencyInjection/Compiler/AddRenderersPass.php

This PR removes an array that is only written to. If we don't read it, we don't need it. 🤓

Remove dead code

---

src/DependencyInjection/Compiler/AddVotersPass.php

This is a minor performance improvement. Calling `array_merge()` directly should be slightly faster than using `call_user_func_array()` for that matter.

Use a variadic call instead of call_user_func_array()

---

tests/DependencyInjection/Compiler/AddExtensionsPassTest.php
tests/DependencyInjection/Compiler/AddProvidersPassTest.php
tests/DependencyInjection/Compiler/AddRenderersPassTest.php
tests/DependencyInjection/Compiler/AddVotersPassTest.php

The testsuite currently fails when run against Symfony 5.1 because of internal changes in Symfony's `ContainerBuilder`.
The failing tests mock the `ContainerBuilder` class. This PR removes those mocks, which should render the tests more robust and readable.

Run tests against a real ContainerBuilder

---

docs/events.rst

Dispatch now takes the event first, and event name second.

Switch the parameter order for the event example

---

.symfony.bundle.yaml

Symfony.com recently launched a new bundle section: https://symfony.com/bundles
This bundle needs to add some configuration in order to be visible on this website. This used to be configured in an internal repository, but the bundle is now able to change the doc versioning in their own repository.
cc @garak

Add configuration for symfony.com's bundle section

---

composer.json
tests/DependencyInjection/Compiler/MenuBuilderPassTest.php
tests/DependencyInjection/Compiler/RegisterMenusPassTest.php

The behavior of tests is the same but now we don't mock what we don't own.
Also it solves the problem with prophecy and php 8 static return type.
wdyt @stof @garak

Refactor tests to not rely on external mock classes

---

.symfony.bundle.yaml

This option must be called `branches` in plural even if it only includes one. Found while building docs for this bundle:
```
// repos/KnpLabs/KnpMenuBundle/contents/.symfony.bundle.yaml config has the following validation errors.
branches: This value should not be blank.
```

Update Symfony bundle config

---

.github/workflows/build.yaml
CHANGELOG.md
composer.json
phpunit.xml.dist
src/DependencyInjection/Compiler/AddExtensionsPass.php
src/DependencyInjection/Configuration.php
src/Provider/BuilderAliasProvider.php
tests/DependencyInjection/Compiler/MenuBuilderPassTest.php
tests/DependencyInjection/Compiler/RegisterMenusPassTest.php
tests/DependencyInjection/ConfigurationTest.php
tests/Provider/BuilderAliasProviderTest.php
tests/Stubs/Child/Menu/Builder.php
tests/Stubs/Menu/Builder.php
tests/Stubs/Menu/ContainerAwareBuilder.php
tests/Stubs/TestKernel.php

A first step for PHP >= 7.4
see https://github.com/KnpLabs/KnpMenuBundle/issues/449
Of course should be wait until this PR is released. https://github.com/KnpLabs/KnpMenu/pull/365 
I am not sure about changes in GitHub Actions.
https://github.com/KnpLabs/KnpMenuBundle/blob/master/src/Templating/Helper/MenuHelper.php is spared from changes to avoid BC breaks. Is this correct or can i change that file?

feat: bump minimum php version to 7.4

---

.github/workflows/build.yaml
CHANGELOG.md
composer.json
docs/index.rst
src/DependencyInjection/KnpMenuExtension.php
src/Provider/BuilderAliasProvider.php
tests/DependencyInjection/KnpMenuExtensionTest.php
tests/Provider/BuilderAliasProviderTest.php
tests/Templating/MenuHelperTest.php

deprecate templating component

---

.github/workflows/build.yaml
CHANGELOG.md
composer.json
phpunit.xml.dist
tests/DependencyInjection/Compiler/AddVotersPassTest.php
tests/DependencyInjection/ConfigurationTest.php
tests/DependencyInjection/KnpMenuExtensionTest.php
tests/Templating/MenuHelperTest.php

migrate phpunit.xml.dist to version 10
allow PHPUnit 11
The change to Attributes, is to fix the deprecation warnings from PHPUnit 11
Maybe it is already time to drop support for php 8.0
https://github.com/KnpLabs/KnpMenuBundle/pull/460#issuecomment-1761147457

feat: drop support for php 8.0

---

src/KnpMenuBundle.php

Without the proper definition of the bundle path, the templates are not discovered by TwigBundle when placed in the new location.
Closes #476

Fix the bundle path to support the new bundle structure

---

.github/workflows/build.yaml
src/DependencyInjection/Compiler/AddExtensionsPass.php
src/DependencyInjection/Compiler/AddProvidersPass.php
src/DependencyInjection/Compiler/AddRenderersPass.php
src/DependencyInjection/Compiler/AddVotersPass.php
src/DependencyInjection/Compiler/MenuBuilderPass.php
src/DependencyInjection/Compiler/RegisterMenusPass.php
src/DependencyInjection/KnpMenuExtension.php
src/Provider/BuilderAliasProvider.php
src/Templating/Helper/MenuHelper.php
tests/Provider/BuilderAliasProviderTest.php
tests/Stubs/Menu/ContainerAwareBuilder.php

See https://github.com/OskarStark/php-cs-fixer-ga/issues/113

fix fixer check in CI

---

composer.json
docs/events.rst
docs/index.rst
docs/menu_builder_service.rst
docs/menu_convention.rst
docs/menu_service.rst
src/DependencyInjection/KnpMenuExtension.php

TODO: change the composer requirement after releasing KnpMenu 3.8.0
Closes #466
Closes #368
Closes #494 (not showing the bundle alias provider as the easy method anymore, and documenting it does not work in a Flex skeleton that has no bundle)

Add support for autoconfiguring menu builder with `[AsMenuBuilder]`
